import type { NextPage } from 'next'
import Head from 'next/head'
import { themeClass } from '../theme/theme.css';
import Button from '../components/theButton/theButton'; 
import Code from '../components/theCode/theCode'; 
import Stack from '../components/theStack/theStack'; 

const ButtonsPage: NextPage = () => {
  const data = [
    {
      id: 1,
      props: [{
        variant: 'primary'
      }]
    },
    {
      id: 2,
      props: [{
        color: 'accent',
      }]
    },
    {
      id: 3,
      props: [{
        color: 'subdued',
      }]
    },
    {
      id: 4,
      props: [{
        color: 'muted',
      }]
    },
    {
      id: 5,
      props: [{
        color: 'accent'
      },
      {
        variant: 'primary'
      }]
    },
    {
      id: 6,
      props: [{
        color: 'subdued',
      },
      {
        variant: 'primary'
      }]
    },
    {
      id: 7,
      props: [{
        color: 'muted',
      },
      {
        variant: 'primary'
      }]
    },
    {
      id: 8,
      props: [{
        variant: 'secondary'
      }]
    },
    {
      id: 10,
      props: [{
        color: 'accent',
      },
      {
        variant: 'secondary'
      }]
    },
    {
      id: 11,
      props: [{
        color: 'subdued',
      },
      {
        variant: 'secondary'
      }]
    },
    {
      id: 12,
      props: [{
        color: 'muted',
      },
      {
        variant: 'secondary'
      }]
    },
  ];
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={themeClass}>

        <Code background='transparent' padding='small'>Component</Code>
        <Code background='transparent'>Props</Code>


        {data.map((item, index) => {
          
          const { props } = item;

          return (
            <Stack key={index}>
              <Stack direction="inline">
                <Button
                >
                  Button
                </Button>
        
                {props.map((prop, propKey) => <Code key={`prop-${propKey}`}>
                  {`${Object.keys(prop)}: ${Object.values(prop)}`}
                </Code>)}
              </Stack>
            </Stack>
          )
        })}

      </section>
    </>

  )
}

export default ButtonsPage
