import type { NextPage } from 'next'
import Head from 'next/head'
import { themeClass } from '../theme/theme.css';
import Button from '../components/button/button'; 

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={themeClass}>
        <Button 
          variant="primary" 
        >
          primary
        </Button>

        <hr/>

        <Button 
          color="accent" 
        >
          accent
        </Button>
        
        <Button 
          color="subdued" 
        >
          subdued
        </Button>

        <Button 
          color="muted" 
        >
          muted
        </Button>

        <hr/>

        <Button 
          color="accent" 
          variant="primary"
        >
          primary | accent
        </Button>
        
        <Button 
          color="subdued" 
          variant="primary"
        >
          primary | subdued
        </Button>

        <Button 
          color="muted" 
          variant="primary"
        >
          primary | muted
        </Button>

        <hr/>

        <Button 
          variant="secondary"
        >
          secondary
        </Button>

        <hr/>

        <Button 
          color="accent" 
          variant="secondary"
        >
          secondary | accent
        </Button>

        <Button 
          color="subdued" 
          variant="secondary"
        >
          secondary | subdued
        </Button>

        <Button 
          color="muted" 
          variant="secondary"
        >
          secondary | muted
        </Button>

        <hr/>

      </section>
    </>

  )
}

export default Home
